### ISSUE TITLE
Category Suggestion

### ISSUE THREAD

**Issue by koqel** [layeredy/uptimematrix-core-issues#6]
Make it so that you can put categories within a category, so like you could have a category for VPS, then you open it and have Shared CPU and Dedicated CPU, and then underneath those you can add the status for each thing under it

I guess this should probably be a premium feature

**Comment by imlayered** [comment]
would take a pretty big amount of changes to core, spark, and pulse; probably will not be doing this until a later point

**Comment by imlayered** [comment]
i'm going to close this for now but it may be revisited in the future, this should be able to happen if someone were to create a version of spark or pulse with this functionality but i will not be implementing this until more important stuff has been fixed/finished
